### ISSUE TITLE
I think

### ISSUE THREAD

**Issue by ghost** [Vanollope/Order-Summary-Component-Challenge#1]
firstly sorry for my english secondly i don't think it's showing because you don't have a folder called 'images', and your div with the 'container' class has a top -1200px, this takes the content and jump out.
and the 'pattern-background', you can put it in css, and it doesn't count as a... text, you know, won't sort because the image will be in the background.

you can place the '.background-image' inside the '.body' content, or, use the '.body' as the background. 
`.body { background-image: url('images/pattern-background-desktop.svg'); background-repeat: no-repeat; }`

at the beginning of the css file, you can use a '*' to select all items in the document, just something that makes me think of all the work it took to write all the selections.

`* { margin: 0; padding: 0; }`

it's just something i think, i don't have really have much coding experience
then that's it

**Comment by Vanollope** [comment]
Thank you for your help! It was indeed the `top: -1200px` that made it not appear. 
For the images though I don't think I can upload folders here? or is there a way to create a folder?

**Comment by Vanollope** [comment]
> firstly sorry for my english secondly i don't think it's showing because you don't have a folder called 'images', and your div with the 'container' class has a top -1200px, this takes the content and jump out.
> and the 'pattern-background', you can put it in css, and it doesn't count as a... text, you know, won't sort because the image will be in the background.
> 
> you can place the '.background-image' inside the '.body' content, or, use the '.body' as the background.
> `.body { background-image: url('images/pattern-background-desktop.svg'); background-repeat: no-repeat; }`
> 
> at the beginning of the css file, you can use a '*' to select all items in the document, just something that makes me think of all the work it took to write all the selections.
> 
> `* { margin: 0; padding: 0; }`
> 
> it's just something i think, i don't have really have much coding experience
> then that's it

Thank you for your help! It was indeed the `top: -1200px` that made it not appear.
For the images though I don't think I can upload folders here? or is there a way to create a folder?

**Comment by ghost** [comment]
> Thank you for your help! It was indeed the `top: -1200px` that made it not appear.
> For the images though I don't think I can upload folders here? or is there a way to create a folder?

but of course it can, as far as I know many files which are used in day-to-day can be sent here, including folders, if the folder is right from its exercise but has not been sent, type 'git status' to see if there is something, if you don't have the folder, put it and add them with 'git add .' (the '.' is needed to add every file that is in the folder but has not been uploaded, in case you are uncertain which files will be uploaded, just type 'git status').

and to align it to the center, you don't need the `margin: 25% 0;` in the '.container'
